In [180]:
print("Hello World")

Hello World


In [181]:
import numpy as np

In [182]:
arr = np.array([[1,2,3],[4,5,6]])

In [183]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [184]:
type(arr)

numpy.ndarray

In [185]:
print(arr.ndim)

2


In [186]:
print(arr.shape)

(2, 3)


In [187]:
print(arr.size)

6


In [188]:
print(arr.dtype)

int32


In [189]:
arr.dtype

dtype('int32')

In [190]:
arr.size

6

In [191]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [192]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [193]:
a.size

9

In [194]:
a.shape

(3, 3)

In [195]:
c = np.zeros((3,4))

In [196]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [197]:
c.dtype

dtype('float64')

In [198]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# np.eye(4)

In [200]:
np.arange(0, 30, 4)

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [201]:
np.linspace(0, 30, 4)

array([ 0., 10., 20., 30.])

In [202]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [203]:
a = np.array([[1,2,3,4],[4,5,6,5],[7,8,9,5]])
new_arr = a.reshape((4,3))

In [204]:
new_arr

array([[1, 2, 3],
       [4, 4, 5],
       [6, 5, 7],
       [8, 9, 5]])

In [205]:
new_arr.flatten()

array([1, 2, 3, 4, 4, 5, 6, 5, 7, 8, 9, 5])

In [206]:
new_arr[1:,:3]

array([[4, 4, 5],
       [6, 5, 7],
       [8, 9, 5]])

In [207]:
new_arr

array([[1, 2, 3],
       [4, 4, 5],
       [6, 5, 7],
       [8, 9, 5]])

In [208]:
new_arr[2:,:3]

array([[6, 5, 7],
       [8, 9, 5]])

In [209]:
new_arr[:,:-1]

array([[1, 2],
       [4, 4],
       [6, 5],
       [8, 9]])

In [210]:
cond = new_arr>5

In [211]:
cond

array([[False, False, False],
       [False, False, False],
       [ True, False,  True],
       [ True,  True, False]])

In [212]:
new_arr

array([[1, 2, 3],
       [4, 4, 5],
       [6, 5, 7],
       [8, 9, 5]])

In [213]:
new_arr+1

array([[ 2,  3,  4],
       [ 5,  5,  6],
       [ 7,  6,  8],
       [ 9, 10,  6]])

In [214]:
new_arr-1

array([[0, 1, 2],
       [3, 3, 4],
       [5, 4, 6],
       [7, 8, 4]])

In [215]:
new_arr

array([[1, 2, 3],
       [4, 4, 5],
       [6, 5, 7],
       [8, 9, 5]])

In [216]:
new_arr*3

array([[ 3,  6,  9],
       [12, 12, 15],
       [18, 15, 21],
       [24, 27, 15]])

In [217]:
new_arr/2

array([[0.5, 1. , 1.5],
       [2. , 2. , 2.5],
       [3. , 2.5, 3.5],
       [4. , 4.5, 2.5]])

In [218]:
new_arr.T

array([[1, 4, 6, 8],
       [2, 4, 5, 9],
       [3, 5, 7, 5]])

In [219]:
new_arr.max()

9

In [220]:
new_arr.max(axis = 1)

array([3, 5, 7, 9])

In [221]:
new_arr.max(axis = 0)

array([8, 9, 7])

In [222]:
new_arr.min(axis = 1)

array([1, 4, 5, 5])

In [223]:
np.sort(new_arr, axis = None)

array([1, 2, 3, 4, 4, 5, 5, 5, 6, 7, 8, 9])

In [224]:
np.sort(new_arr, axis = 0)

array([[1, 2, 3],
       [4, 4, 5],
       [6, 5, 5],
       [8, 9, 7]])

In [225]:
np.sort(new_arr, axis = 1)

array([[1, 2, 3],
       [4, 4, 5],
       [5, 6, 7],
       [5, 8, 9]])

In [226]:
np.sort(new_arr, axis = 0,kind = "mergesort")

array([[1, 2, 3],
       [4, 4, 5],
       [6, 5, 5],
       [8, 9, 7]])

In [227]:
new_arr

array([[1, 2, 3],
       [4, 4, 5],
       [6, 5, 7],
       [8, 9, 5]])

In [228]:
np.sort(new_arr, axis = 1,kind = "mergesort")

array([[1, 2, 3],
       [4, 4, 5],
       [5, 6, 7],
       [5, 8, 9]])

In [229]:
ar1 = np.array([[1,2],[2,3]])
ar2 = np.array([[4,5],[6,7]])

In [230]:
np.vstack((ar1,ar2))

array([[1, 2],
       [2, 3],
       [4, 5],
       [6, 7]])

In [231]:
np.hstack((ar1,ar2))

array([[1, 2, 4, 5],
       [2, 3, 6, 7]])

In [232]:
np.row_stack((ar1,ar2))

array([[1, 2],
       [2, 3],
       [4, 5],
       [6, 7]])

In [233]:
arr1 = np.column_stack((ar1,ar2))

In [234]:
arr1

array([[1, 2, 4, 5],
       [2, 3, 6, 7]])

In [235]:
arr1[0]

array([1, 2, 4, 5])

In [236]:
np.concatenate((ar1,ar2),1)

array([[1, 2, 4, 5],
       [2, 3, 6, 7]])

In [237]:
np.hsplit(arr1,2)

[array([[1, 2],
        [2, 3]]),
 array([[4, 5],
        [6, 7]])]

In [238]:
np.min(arr1)

1

In [239]:
np.max(arr1)

7

In [240]:
np.mean(arr1)

3.75

In [241]:
np.median(arr1)

3.5

In [242]:
np.average(arr1)

3.75