# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [5]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Bharath Kumar/anaconda3/Library/include
    lib directory: C:/Users/Bharath Kumar/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: wi

#### 3. Create a null vector of size 10

In [11]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [15]:
arr1.nbytes

80

5.  How to get the documentation of the numpy add function from the command line?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [15]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [21]:
arr1 = np.arange(10,50)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [27]:
arr = [1,2,3,4,5]
arr[::-1]

[5, 4, 3, 2, 1]

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [29]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [40]:
arr = [1,2,0,0,4,0]
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [50]:
import random
np.random.random((3,3,3))

array([[[0.12286041, 0.59581586, 0.07214076],
        [0.57710864, 0.41736079, 0.23726506],
        [0.81068814, 0.10113402, 0.7806845 ]],

       [[0.23427177, 0.04114737, 0.24808422],
        [0.35822767, 0.95150711, 0.24706081],
        [0.04174245, 0.17660511, 0.49335779]],

       [[0.09973212, 0.73820763, 0.21427655],
        [0.00643608, 0.24801981, 0.33372911],
        [0.34985697, 0.64702259, 0.44780275]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [70]:
arr = np.random.random((10,10))
arr

array([[0.5421344 , 0.96410873, 0.00169149, 0.48131445, 0.27131104,
        0.03891742, 0.28413381, 0.43227392, 0.0873061 , 0.09065772],
       [0.41042997, 0.87314787, 0.62787582, 0.85948494, 0.11825   ,
        0.08553115, 0.17991634, 0.94011   , 0.91399346, 0.4430519 ],
       [0.70395449, 0.50373551, 0.10840986, 0.32049851, 0.35203386,
        0.51524713, 0.10258793, 0.22402467, 0.51336546, 0.66470377],
       [0.07043379, 0.21456337, 0.83056578, 0.77092887, 0.68169408,
        0.58813926, 0.97383675, 0.23450251, 0.35068177, 0.64084795],
       [0.87084569, 0.9557895 , 0.53111822, 0.61627884, 0.5050593 ,
        0.63396875, 0.06288939, 0.02411961, 0.14882717, 0.01537234],
       [0.04032838, 0.07365709, 0.71507755, 0.18013365, 0.49129917,
        0.49671357, 0.31419706, 0.64825699, 0.85175375, 0.22880818],
       [0.52488573, 0.04909186, 0.6208834 , 0.69542306, 0.46152837,
        0.90960904, 0.25955026, 0.949047  , 0.27456953, 0.10495525],
       [0.08217445, 0.46025665, 0.4504569

In [66]:
np.max(arr)

0.994663869160723

In [68]:
np.min(arr)

0.000804733237773414

#### 14. Create a random vector of size 30 and find the mean value

In [76]:
arr = np.random.random((30))
arr

array([0.81154695, 0.08324832, 0.93759149, 0.89963742, 0.48856071,
       0.14002275, 0.92103153, 0.07394341, 0.33029057, 0.28075204,
       0.12898447, 0.98427858, 0.49703632, 0.32695176, 0.05304575,
       0.24725144, 0.35954955, 0.89732843, 0.13696701, 0.82321157,
       0.28462326, 0.65779768, 0.02568033, 0.82996037, 0.61790162,
       0.37347019, 0.3107332 , 0.91538609, 0.42677843, 0.82305147])

In [78]:
np.mean(arr)

0.4895537570339236

#### 15. Create a 2d array with 1 on the border and 0 inside

In [82]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [90]:
arr1 = np.pad(arr, pad_width=1, constant_values=0)
arr1

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [92]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [112]:
matrix = np.zeros((5, 5))
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])
matrix

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [116]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
checkerboard

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [128]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
